function delta_r = miss_distance( ... 
        X0, rf, acc_hist, dtau, N, order, ... 
        cSun, caseSun, alphaSun, caseStark, divSafeguard, ... 
        accuracyFlag, Xf, accuracyOut, statusFlag ) 

    [ X_hist, ~, ~, ~ ] = FGStark_Nstep_ctrl_prop( ... 
        X0, acc_hist, dtau, N, order, ... 
        cSun, caseSun, alphaSun, caseStark, divSafeguard, ... 
        accuracyFlag, Xf, accuracyOut, statusFlag ) ; 
    
    Xf_prop = X_hist(end,:) ; 
    
    delta_r = norm( Xf_prop(1:3) - rf ) ; 
    
end 
    
